# Generated by Django 4.2.6 on 2024-02-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_alter_blog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='body_description',
            field=models.TextField(default='test', max_length=2000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_description',
            field=models.TextField(max_length=50),
        ),
    ]
